---
MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
url: "https://mnowlin.github.io"
indexes:
  category: "categories"
title: Matthew C. Nowlin
CanonifyUrls: true
owner: 
 name: Matthew C. Nowlin
 avatar: me.jpg
 bio: Assistant professor of political science at the College of Charleston
 email: nowlinmc@cofc.edu
 twitter: nowlin_matt
 google_scholar: xu7Y7_QAAAAJ
 github: mnowlin
google_analytics: UA-78078808-1
links:
 - title: Research
   url: /research/
 - title: Teaching
   url: /teaching/
 - title: Notes
   url: /blog/
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
...
