---
MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
baseurl: "https://mnowlin.github.io"
indexes:
  category: "categories"
title: Matthew C. Nowlin
CanonifyUrls: true
owner: 
 name: Matthew C. Nowlin
 avatar: me.jpg
 bio: Assistant professor of political science at the College of Charleston
 email: nowlinmc@cofc.edu
 twitter: nowlin_matt
 google_scholar: xu7Y7_QAAAAJ
 github: mnowlin
google_analytics: UA-78078808-1
menu:
  main:
      - Name: "Publications"
        URL: "/publications"
        Weight: 2
      - Name: "Research"
        URL: "/research"
        Weight: 3
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 4
      - Name: "Blog"
        URL: "/blog"
        Weight: 5
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
...
