# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matthew C. Nowlin 
tagline:          
description:      'Assistant Professor of Political Science at the College of Charleston'
url:              http://mnowlin.github.io

author:
  name:           'Matthew Nowlin'
  url:            https://twitter.com/nowlin_matt

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mnowlin/mnowlin.github.io
