# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matthew Nowlin 
tagline:          
description:      
url:              http://mnowlin.github.io
baseurl:          /

author:
  name:           'Matthew C. Nowlin'
  url:            https://twitter.com/nowlin_matt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mnowlin/mnowlin.git.io
