---
MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
baseurl: "https://mnowlin.github.io"
indexes:
  category: "categories"
title: "matthewcnowlin.com"
CanonifyUrls: true
menu:
  main:
      - Name: "Publications"
        URL: "/publications"
        Weight: 2
      - Name: "Research"
        URL: "/research"
        Weight: 3
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 4
      - Name: "Blog"
        URL: "/blog"
        Weight: 5
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
...
