baseurl = "http://matthewcnowlin.com/"
title = "Matthew C. Nowlin"
copyright = "&copy; 2016 Matt Nowlin"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-78078808-1"


[params]
    name = "Matthew C. Nowlin"
    role = "Assistant Professor of Political Science"
    organization = "College of Charleston"
    interests = ["Policymaking Process", "Environmental Policy", "Science and Public Policy", "Policy and Public Opinion"]
    email = "nowlinmc@cofc.edu"
    address = "Department of Political Science, 114 Wentworth, Charleston, SC 29414."
    phone = "843 953 0279"

    # Date format (refer to Go's date format: http://flippinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "Mon, Jan 2, 2006"

    # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
    math = false

    # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
    custom_css = []
    custom_js  = []

    [[params.education]]
        course = "PhD in Political Science"
        institution = "University of Oklahoma"
        year = 2013

    [[params.education]]
        course = "MA in Political Science"
        institution = "University of Central Oklahoma"
        year = 2008

    [[params.education]]
        course = "BA Psychology"
        institution = "University of Central Oklahoma"
        year = 2003

    [params.contact]
        # Automatically link email and phone?
        autolink = true

    # Social/Academic Networking
    #
    # Icon pack "fa" includes the following social network icons:
    #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
    #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
    #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
    #
    # Icon pack "ai" includes the following academic network icons:
    #   google-scholar, arxiv, orcid, researchgate, mendeley
    #   Full list: https://jpswalsh.github.io/academicons/

    [[params.social]]
        icon = "envelope"
        icon_pack = "fa"
        link = "mailto:nowlinmc@cofc.edu"

    [[params.social]]
        icon = "twitter"
        icon_pack = "fa"
        link = "//twitter.com/nowlin_matt"

    [[params.social]]
        icon = "google-scholar"
        icon_pack = "ai"
        link = "https://scholar.google.com/citations?user=xu7Y7_QAAAAJ&hl=en"

    [[params.social]]
        icon = "github"
        icon_pack = "fa"
        link = "//github.com/mnowlin"


# Navigation Links
#
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
    name = "Home"
    url = "#top"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "#publications"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 3

[[menu.main]]
    name = "Research"
    url = "#research"
    weight = 4

[[menu.main]]
    name = "Teaching"
    url = "#teaching"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 6
